name: Docker build and shellcheck

on: [push, pull_request]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
    #   - name: shellcheck
    #     run: shellcheck nextcloud/rootfs/usr/bin/run.sh
      - name: build docker files
        run: docker run --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v ~/.docker:/root/.docker -v "$(pwd)":/data homeassistant/amd64-builder	-t nextcloud --amd64 --test
      - name: publish docker files
        if: github.event_name != 'pull_request'
        run: docker run --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v ~/.docker:/root/.docker -v "$(pwd)":/data homeassistant/amd64-builder	-t nextcloud --amd64 --release-tag --docker-user sabuto --docker-password ${{ secrets.DOCKER_PASSWORD }}
